rtabmap:
  ros__parameters:

    # Standard ROS 2 parameters (Booleans and Strings)
    use_sim_time: true
    frame_id: "base_link"

    # Subscription flags (Booleans)
    subscribe_depth: true
    subscribe_rgb: true
    subscribe_scan: false
    approx_sync: true

    # RTAB-Map parameters:
    RGBD/NeighborLinkRefining: "true"
    Grid/FromDepth: "true"
    Mem/IncrementalMemory: "true"
    Mem/InitWMWithAllNodes: "false"

    Grid/RangeMax: "10.0"       
    Reg/Strategy: "0"          
    Vis/MinInliers: "40"   # previous=15    
    Vis/InlierDistance: "0.05"
    Mem/RehearsalSimilarity: "0.45"
    RGBD/ProximityBySpace: "false"
    Grid/MaxGroundHeight: "0.1"
    RGBD/LoopClosureReextractFeatures: "true"
    Vis/MinInliersDistribution: "0.1"
    
    Kp/DetectorStrategy: "1"
    Kp/MaxFeatures: "1000"
    Kp/MaxDepth: "3.0"

    RGBD/OptimizeMaxError: "0.1"


    # Grid/NormalK:
    # Grid/GroundIsObstacle:
    # Grid/FlatObstacleDetected: